### ISSUE TITLE
Change image format from Png to WebP

### ISSUE THREAD

**Issue by AnirudhPanda** [Praful932/Kitabe#72] opened 2021-03-12 12:11 UTC
**Describe the bug**
Image formats like JPEG 2000, JPEG XR, and WebP often provide better compression than PNG or JPEG, which means faster downloads and less data consumption.  Kitabe mostly uses jpg and png image formats which affect the website's overall performance.

**Expected behavior**
Faster Reloads

**Are you willing to contribute to this issue?** [Yes]
I am a GSSOC participant.

**Comment by vidhi1121** [comment] 2021-03-12 12:39
I am participant in GSSOC'21.Can you please assign this to me?

**Comment by Praful932** [comment] 2021-03-13 05:28
@AnirudhPanda Thanks for your interest in the project. If you can update your issue with an example image(before/after with size) from the project itself that would be great

**Comment by AnirudhPanda** [comment] 2021-03-13 17:03
Sure!

![Screenshot (115)](https://user-images.githubusercontent.com/66218496/111037717-67928000-844b-11eb-9364-b6619ddc3df8.png)

**Left** is the original PNG image whose size is _621kb_ and to the **right** is the modified WebP version whose size is _152kb_.

**Comment by Praful932** [comment] 2021-03-13 17:05
Go ahead @AnirudhPanda

**Comment by simranbhalla3** [comment] 2021-03-14 08:21
hii, Can you please assign thi sissue to me, i am a gssoc participant and would love to work on this issue

**Comment by maneprajakta** [comment] 2021-04-01 03:26
@AnirudhPanda any updates?

**Comment by Greeshma2903** [comment] 2021-04-05 15:54
@Praful932  @maneprajakta  I would like to work on it. 
Can I use an online image converter? Like this: https://cloudconvert.com/png-to-webp

**Comment by Greeshma2903** [comment] 2021-04-05 15:57
> @Praful932 @maneprajakta I would like to work on it.
> Can I use an online image converter? Like this: https://cloudconvert.com/png-to-webp

I used it to convert one of the banner images. The .png version is 372 KB whereas .webp version is 69.7 KB (size).

**Comment by maneprajakta** [comment] 2021-04-05 17:07
> @Praful932 @maneprajakta I would like to work on it.
> Can I use an online image converter? Like this: https://cloudconvert.com/png-to-webp

Yes, go for it.

**Comment by Praful932** [comment] 2021-04-07 17:47
@maneprajakta Shall we make this level0 the issue is a piece of cake thats why

**Comment by maneprajakta** [comment] 2021-04-08 03:19
@Praful932 Yep no issues.

**Comment by maneprajakta** [comment] 2021-04-10 13:54
Closed by #182

**Closed by maneprajakta** 2021-04-10 13:54 UTC
Labels: GSSOC21, Level0, assigned, enhancement, priority:medium, ui/ux
