### ISSUE TITLE
Tooltip & Icon Fix

### ISSUE THREAD

**Issue by Sristi27** [Praful932/Kitabe#137] opened 2021-03-22 12:39 UTC
**Is your feature request related to a problem? Please describe.**
The navbar icons can be made to look better and also the login/signup form.

**Describe the solution you'd like**
The icons in the navbar look bigger and not appealing to the user.Also,the signin signup pages can be made more attractive.It has a lot of vacant space which can be used to add relevant images or inspire the user to actually make an account on our platform.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Describe alternatives you've considered**
I would like to work on this issue and create more user appealing UI along with form restructuring.

**Comment by Praful932** [comment] 2021-03-22 16:32
@Sristi27 We already have a ongoing PR for signup,login page #108, Could you add some examples of how the navbar icons will be improved

**Comment by Sristi27** [comment] 2021-03-22 16:37
@Praful932 

Instead of adding a name below each icon,we can show it on tooltip,that would reduce the height of the navbar as well and the icons could be made a bit smaller.

Also after getting the searched book the form could be reset to original.

Also,a search icon could be added in the search box with the inner padding reduced a bit.

**Comment by maneprajakta** [comment] 2021-03-23 03:25
@Sristi27 go ahead with this one.
Also before starting go through Very Important Points to be Noted section in [Satrter Guide](https://github.com/Praful932/Kitabe/discussions/42).
- First show us a mockup and also maintain the theme of website.

**Comment by simranbhalla3** [comment] 2021-03-23 07:51
Hi i am a gssoc participant , can i work on this issue? I have experience in css and js

**Comment by maneprajakta** [comment] 2021-03-23 11:22
@simranbhalla3 thank you for showing interest the issue is already assigned. Meanwhile, you can check other issues which are unassigned.

**Comment by Sristi27** [comment] 2021-03-23 20:00
I am having issues running it on my machine with all the python dependencies installation.Some help would be great!

**Comment by Sristi27** [comment] 2021-03-23 20:01
@maneprajakta @Praful932

**Comment by maneprajakta** [comment] 2021-03-24 03:30
Ya @Sristi27  project supports python version 3.8 you can download it from  [here](https://www.python.org/downloads/windows/).
If you still face a problem reach out to us on discord or start a Github discussion.

**Comment by Praful932** [comment] 2021-03-27 17:40
@Sristi27 Any updates? You can open a WIP/Draft PR so we can track that you are going in the right direction :)

**Comment by maneprajakta** [comment] 2021-04-05 17:11
@Sristi27 any updates ?

**Comment by Sristi27** [comment] 2021-04-05 19:49
> @Sristi27 any updates ?

Created a Pull Request.Please review it and see if any further updates are required!

**Comment by Sristi27** [comment] 2021-04-07 19:49
@Praful932  @maneprajakta Please kindly review my pull request #180

**Comment by maneprajakta** [comment] 2021-04-17 03:18
@Praful932 closing this issue after #56 we will think about nav-bar.

**Closed by maneprajakta** 2021-04-17 03:18 UTC
Labels: GSSOC21, Level2, assigned, enhancement, priority:medium, ui/ux
