### ISSUE TITLE
Adding a Search Icon in the Search bar

### ISSUE THREAD

**Issue by Sweeti-Gupta** [Praful932/Kitabe#111] opened 2021-03-17 11:03 UTC
**Is your feature request related to a problem? Please describe.**
No, my feature request is not related to any problem. It's about making the page more attractive.

**Describe the solution you'd like**
I want to add a "Search Icon" in the "Search Bar" to give a better look to the project.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Describe alternatives you've considered**
As of now, I have no alternatives for this, I just want to add a "Search Icon" in the "Search Bar".

**Additional context**
![Screenshot (2706)_LI](https://user-images.githubusercontent.com/79096136/111525614-d2152a00-8783-11eb-9132-afc6705528e2.jpg)

@maneprajakta I want to contribute this as a part of GSSOC'21.Please assign this issue to me.

**Comment by maneprajakta** [comment] 2021-03-17 12:41
@Sweeti-Gupta Please follow the issue template for creating an issue.

**Comment by Sweeti-Gupta** [comment] 2021-03-17 19:22
**Is your feature request related to a problem? Please describe.**
No, my feature request is not related to any problem. It's about making the page more attractive.

**Describe the solution you'd like**
I want to add a "Search Icon" in the "Search Bar" to give a better look to the project.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Describe alternatives you've considered**
As of now, I have no alternatives for this, I just want to add a "Search Icon" in the "Search Bar".

**Additional context**
![Screenshot (2706)_LI](https://user-images.githubusercontent.com/79096136/111525614-d2152a00-8783-11eb-9132-afc6705528e2.jpg)

@maneprajakta I want to contribute this as a part of GSSOC'21.Please assign this issue to me.

**Comment by maneprajakta** [comment] 2021-03-18 03:07
Go for it @Sweeti-Gupta.
Before starting go through [Starter Guide](https://github.com/Praful932/Kitabe/discussions/42) it will help you in contributing to the project.

**Comment by Sweeti-Gupta** [comment] 2021-03-18 13:02
@maneprajakta Ok Ma'am! Thank you for assigning.

**Comment by ambivert-sam** [comment] 2021-03-18 19:33
@maneprajakta mam can you please assign this issue to me?

**Comment by maneprajakta** [comment] 2021-03-19 02:50
@ambivert-sam Thank you for showing interest but the issue is already assigned to someone.

**Comment by Praful932** [comment] 2021-03-19 15:07
@ambivert-sam Go through the [starter guide](https://github.com/Praful932/Kitabe/discussions/42) :)

**Comment by maneprajakta** [comment] 2021-03-20 16:50
@Sweeti-Gupta any updates?

**Comment by Sweeti-Gupta** [comment] 2021-03-21 06:17
@maneprajakta Working on it.

**Comment by iampranavdhar** [comment] 2021-03-26 19:55
Hey @maneprajakta,
In case if it is not solved yet can you assign me?
Thanks

**Comment by Praful932** [comment] 2021-03-27 17:44
Hi @iampranavdhar This is currently assigned :)
Check out the [starter guide](https://github.com/Praful932/Kitabe/discussions/42) or [up-for-grab issues](https://github.com/Praful932/Kitabe/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-asc+no%3Aassignee)

**Closed** 2021-03-31 03:30 UTC
Labels: GSSOC21, Level2, assigned, enhancement, good first issue, priority:low, ui/ux
