### ISSUE TITLE
[GSSOC'21] Profile page is not there

### ISSUE THREAD

**Issue by machine-sg** [Praful932/Kitabe#53] opened 2021-03-10 06:50 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Are you willing to contribute to this issue?** [Yes/No]

**Describe alternatives you've considered**

**Additional context**

I want to add the profile page of the reader as a participant of GSSOC'21. Please assign me this one.

**Comment by YasviPatel** [comment] 2021-03-10 07:05
hiii @machine-sg I am interested in this.I am participate at GSSoC'21.Would you please assign this issue to me???

**Comment by thesakshipandey** [comment] 2021-03-10 13:03
I can work on this issue, can you assign me this issue?

**Comment by ShrutiKhatri826** [comment] 2021-03-10 15:30
I am a GSSOC'21 participant. I would love to take on this issue. Can you please assign it to me? Hope to hear from you soon!

**Comment by maneprajakta** [comment] 2021-03-10 16:43
@machine-sg The issue is not clear can you edit the description of the issue and make it more clear. If we don't hear back from you in 3 days we will close this issue.

**Comment by maneprajakta** [comment] 2021-03-10 16:46
@YasviPatel @thesakshipandey @ShrutiKhatri826 Thanks for showing interest :star: . But as the issue is not clear we are not assigning anyone to this. Meanwhile, you can go through our [Starte Guide](https://github.com/Praful932/Kitabe/discussions/42) to get a more clear view of the project and how to contribute to it  :smiley: .

**Closed** 2021-03-13 13:36 UTC
Labels: need-clarity
