### ISSUE TITLE
Fix "Sign In with Google"

### ISSUE THREAD

**Issue by nidhivanjare** [Praful932/Kitabe#162] opened 2021-03-30 14:54 UTC
**Describe the bug**
The "Sign in with Google" button in the login page in sign-up page is not working. 

**Expected behavior**
I want to fix the error that is thrown when a user clicks sign in with a google button so that he/she can easily sign in. 

**Screenshots**
<img width="1440" alt="Screenshot 2021-03-30 at 8 17 46 PM" src="https://user-images.githubusercontent.com/55665104/113009276-6d030080-9195-11eb-8292-fcc3b4ebab46.png">

<img width="1440" alt="Screenshot 2021-03-30 at 8 17 58 PM" src="https://user-images.githubusercontent.com/55665104/113009260-696f7980-9195-11eb-83de-2699cbec653c.png">

**Are you willing to contribute to this issue?** 
Yes

**Desktop (please complete the following information):**
 - OS: mac OS Big sur 11.2.3
 - Browser : chrome, safari
 - Version : 14.0.3

**Smartphone (please complete the following information):**
 - Device: Iphone Xs Max
 - OS: 14.4.2
 - Browser : safari
 - Version 14.0.3

**Comment by Praful932** [comment] 2021-03-30 16:18
Marking & Closing as duplicate of #161

**Closed by Praful932** 2021-03-30 16:18 UTC
Labels: duplicate
